second_project/my_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'my_app'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.user_login, name='user_login')
]

second_project/my_project_two/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from my_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^my_app/', include('my_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile')
]

second_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    # additional data
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

second_project/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

second_project/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm, UserProfileInfoForm
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.core.urlresolvers import reverse


def index(request):
    return render(request, 'my_app/index.html')


@login_required
def profile(request):
    return render(request, 'my_app/profile.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found profile pic')
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'my_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('profile'))
            else:
                return HttpResponse('User is not active')
        else:
            print('someone tried to login your account and failed')
            print("user:{} pass:{}".format(username, password))
            return HttpResponse('Invalid password and username')

    else:
        return render(request, 'my_app/login.html', {})

second_project/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href='{% static 'css/style.css' %}' />
    <title>Second Project</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand">Home</a>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'my_app:register' %}" class="nav-link">Register</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class='nav-item'><a class='nav-link' href='{% url 'profile' %}'>Profile</a></li>
          {% else %}
          <li class='nav-item'><a class='nav-link' href='{% url 'my_app:user_login' %}'>Login</a></li>

          {% endif %}
        </ul>
      </div>
    </nav>

    <main class="container">{% block content %}{% endblock %}</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

second_project/templates/my_app/index.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  <h1 class="text-center font-italic text-success text-capitalize mb-5">
    Welcome to project two
  </h1>
  <p class="lead text-justify">
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nesciunt illum
    tenetur, unde odio impedit accusamus accusantium nostrum perferendis iste,
    assumenda excepturi nemo doloribus id nobis doloremque, dolores libero eius.
    Veniam repellat, laboriosam facilis quas doloribus illum velit libero
    corrupti id culpa distinctio nulla ipsam quis provident et, repudiandae
    totam! Veniam nostrum, ullam delectus vitae a deleniti itaque voluptatem
    odio id repellat asperiores numquam provident minus, aliquam iusto! Deserunt
    tempore reiciendis exercitationem quis doloremque laudantium nemo modi,
    animi saepe deleniti repellendus impedit culpa est quo voluptatem fugiat
    odit earum ipsam officiis error nostrum. Dignissimos numquam iste excepturi
    ducimus voluptates alias molestiae quos exercitationem? Quas tempora sint
    eveniet aut unde ad sequi dolorum praesentium nulla sit numquam, qui sed
    voluptatem excepturi laudantium iure voluptatibus quibusdam adipisci
    eligendi! Consequatur eum porro atque? Qui atque itaque cum optio commodi
    eveniet eligendi porro facilis accusamus neque hic est voluptatibus aperiam,
    soluta ipsam. Modi, quo quaerat.
  </p>
  <h2 class="text-success">Here is some info:</h2>
  <p class="lead text-justify">
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptatum ea,
    provident facilis exercitationem corporis saepe distinctio fugit, voluptas,
    veniam ipsa officia ad natus possimus sed iusto eligendi. Perspiciatis quos
    odit pariatur blanditiis recusandae veniam eaque voluptate consectetur
    velit. Accusantium alias, repellendus doloremque perspiciatis impedit dolor
    nulla deserunt culpa laudantium cum ipsa fugit ab, modi sapiente nemo
    beatae. Voluptates, eaque. Numquam atque ipsum saepe assumenda nihil dolore
    distinctio esse, itaque tempora quod placeat? Harum, animi optio!
    Consequatur nemo veritatis saepe in quas fugit fugiat? A, placeat. Autem
    praesentium reprehenderit nobis aliquid, labore, itaque at animi deserunt
    sapiente esse non optio facere ab? Quo vel enim natus explicabo ab ipsa
    repudiandae autem cupiditate ipsum. Aliquam dolor ea, consequatur id porro
    numquam culpa labore odio repellendus nam pariatur provident? Dolorum,
    doloremque nisi sint quisquam nam, consequuntur odio optio perspiciatis
    quasi, ipsum cupiditate. Amet, rem! Praesentium natus similique obcaecati
    quis porro libero harum sapiente!
  </p>
</div>
{% endblock %}

second_project/templates/my_app/login.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  <h1 class="text-center text-muted text-capitalize mb-5">Please Login here</h1>
  <form action="{% url 'my_app:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username" />

    <label for="password">Password:</label>
    <input type="password" name="password" />

    <input type="submit" class="btn btn-outline-primary" value="Login" />
  </form>
</div>
{% endblock %}

second_project/templates/my_app/profile.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>Profile</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <a href="{% url 'logout' %}" class="navbar-brand ml-auto">Logout</a>
      </div>
    </nav>

    <main class="container">
      {% block content %}
      <h1 class="text-center text-success mb-5">Welcome to your profile</h1>
      <p class="lead">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas vero
        mollitia harum nostrum ullam libero explicabo accusantium veniam,
        incidunt, nulla ipsam recusandae! Possimus facere aspernatur eos eum rem
        ducimus culpa?
      </p>
      <h2 class="text-success">Post no.1</h2>
      <p class="lead">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos ut
        ea reiciendis magni cupiditate deleniti ipsum vel animi nostrum,
        consequuntur numquam inventore itaque repudiandae omnis dicta rerum odit
        voluptatem labore consequatur pariatur. Perspiciatis sunt ipsam nobis
        explicabo rerum doloremque, totam beatae tenetur hic quia quisquam
        officiis porro consequatur aspernatur dolores?
      </p>
      <h3 class="text-success">Post no.2</h3>
      <p class="lead">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aperiam fugit
        possimus nam. Cum nihil quia atque praesentium consequuntur natus
        necessitatibus quam nulla culpa! Temporibus incidunt eligendi fugit
        odit. Eveniet rem incidunt fuga, suscipit dignissimos temporibus beatae
        hic repellat molestias quas adipisci culpa neque consequuntur mollitia
        quidem, accusamus perferendis ad ab?
      </p>
      <h4 class="text-success">Post no.3</h4>
      <p class="lead">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam
        dolorum obcaecati, adipisci magnam ipsam suscipit facilis quaerat, iste
        temporibus autem sint nemo, cum molestiae? Recusandae possimus itaque,
        similique corporis ab nemo enim eos repellat adipisci ducimus. Molestiae
        iure veniam officia, adipisci nulla natus explicabo maiores provident
        perferendis fugiat autem debitis!
      </p>
      {% endblock %}
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

second_project/templates/my_app/registration.html
<!DOCTYPE html>
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
  {% if registered %}
  <h1 class="text-center text-success display-1">Thanks❤</h1>
  {% else %}
  <div>
    <h1 class="text-muted text-center mb-5">Registration here</h1>
    <h4 class="ml-4 mb-3">Please fillup the form:</h4>
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %} {{user_form.as_p}} {{profile_form.as_p}}
      <input type="submit" class="btn btn-outline-secondary" value="Register" />
    </form>
  </div>
  {% endif %}
</div>
{% endblock %}